name: TODO to Issue

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  issues: write

jobs:
  todo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: alstr/todo-to-issue-action@v4
        with:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LABELS: "todo"
          CLOSE_ISSUES: true
          AUTO_ASSIGN: true
